### ISSUE TITLE
error: matrix multiplication: problem with matrix inverse; suggest to use solve() instead

### ISSUE THREAD

**Issue by timshall** [zilinli1988/SCANG#4]
Hi,

I have been going through the SCANG tutorial and everything is fine until the line:

`res_lm <- SCANG(genotype, obj_nullmodel, Lmin, Lmax, filter=filter, f=f)`

At this point I get the error:

error: matrix multiplication: problem with matrix inverse; suggest to use solve() instead
Error in SCANG_O_Thres(genotypesub, X, working, sigma, fam, obj_nullmodel$times,  : 
    matrix multiplication: problem with matrix inverse; suggest to use solve() instead

I am using R version 4.0.3 and am aware that the example was performed using R version 3.5.1. I am quite unsure as to how this error is appearing but I suspect it is involved with the SCANG_O_Thres.cpp file.

Have you had any issues with this code in R version 4? I have not seen anything regarding any issues Rcpp packages that would cause this error. I am also not an experienced user with Rcpp but it does seem odd that R would intervene and suggest a function that is already being handled in C++.

Please let me know if you want to know anything else about the code I've made from the example code and I look forward to hearing from you.

Tim

**Comment by zilinli1988** [comment]
Hi Tim, Thanks for letting me know. I have never seen this issue before. But I was tested it using R version 3.5.1 and R version 3.6.1. 

I will figure out what happens and fix it if there is an issue for R version 4. 

Thanks very much. 
Sincerely,
Zilin

**Comment by timshall** [comment]
Hi Zilin,

Thanks for the quick response. I've tried it on my end with an older version of R, version 3.6.3 specifically, which is still giving me the same error. So it does not appear to be an isse with versions of R on the face of it.

Error in SCANG_O_Thres(genotypesub, X, working, sigma, fam, obj_nullmodel$times,  : 
  matrix multiplication: problem with matrix inverse; suggest to use solve() instead

Hopefully this helps a little in identifying the issue. It might also be worth noting I am using RStudio if that can be associated with these kinds of errors.

Thanks again,

Tim

**Comment by zilinli1988** [comment]
Hi Tim,

I have tested the SCANG package using the example in the tutorial in the following four settings, and it all worked well without any error:
1. R 3.6.1, 
2. R 4.0.3,
3. R 3.6.1 with Rstudio,
4. R 4.0.3 with Rstudio.

One possible reason for this issue is that your dependency did not support the "inv" function in C++. 

Sincerely,
Zilin

**Comment by zilinli1988** [comment]
Hi Tim,

One possible solution is to avoid using "inv." You could try to use the null model fitting function in our newly published STAARpipeline package (https://github.com/xihaoli/STAARpipeline). You could try to use the following code instead of "obj_nullmodel <- fit_null_glm_SCANG(phenotype~-1+X,data=phenotypedata,family=gaussian(link = "identity"))" in the tutorial

library(STAARpipeline)
id0 <- 1:N
phenotypedata <- data.frame(phenotype=phenotype,X=X,id=id0)
obj_nullmodel <- fit_nullmodel(phenotype~-1+X,data=phenotypedata,family=gaussian(link = "identity"),kins=NULL,id="id")
obj_nullmodel <- staar2scang_nullmodel(obj_nullmodel)

Sincerely,
Zilin

**Comment by timshall** [comment]
Hi Zilin,

Apologies for not providing feedback sooner regarding this and thank you for the suggestions above. I have been trying this out some more but am still running into problems.

As an update regarding the SCANG() function, I have tried the example code on the UKBiobank DNAnexus RAP in JupyterLab with R kernel and am still obtaining the same error as before. I'm going to check out further the suggestion regarding 'inv' you had.

I also tried the STAARpipeline function suggested, however, I am obtaining another error regarding matrix operations:

Error in chol.default(cov) : 
  the leading minor of order 2 is not positive definite
Calls: staar2scang_nullmodel -> <Anonymous> -> <Anonymous> -> chol.default
Execution halted

I'm still investigating what's happening with the new error, but if you have any experience with this already any further suggestions will be a great help. The plan is to use STAARpipeline so if it is worth raising an issue on that GitHub page I can do that also.

Many thanks again and I look forward to hearing from you.

Tim

**Comment by zilinli1988** [comment]
Hi Tim,
 
I think this is a similar problem as before. Both “inv” and “chol” are all basic functions of matrix computation, and it is a problem of your dependency. Since it is the same issue, there is no need to raise an issue on the STAARpipeline GitHub page. 
 
Did you use the example code on the SCANG tutorial page?
 
Thanks very much.
 
Sincerely,
Zilin

**Comment by timshall** [comment]
Hi Zilin,

Yes, this is using the example code on the SCANG tutorial page, with and without the amendment you suggested above.

I've also been able to look into the code in more depth and have found where I think the error is arising from that doesn't immediately appear to be from dependencies. Considering the code as written in the example, at line 51 in SCANG_O_Thres.cpp, specifically the part:

`inv(trans(X)*arma::diagmat(working)*X`

is inversing a matrix for which an inverse doesn't exist. Which I think is caused by the column X.X2 in obj_nullmodel$model being made up of only zeros. Thus, the problem may lie in the glm() function which I'm now having a look at.

Many thanks again for the quick responses,

Tim

**Comment by zilinli1988** [comment]
Hi Tim,

The covariate X2 is generated by "X2 <- rbinom(samplesize,1,1/2)". You could also check whether X2 is all zeros in your case. 

Sincerely,
Zilin

**Comment by timshall** [comment]
Hi Zilin,

Apologies again for my slow responses. The problem was indeed a 0 instead of a 1 in the rbinom() function that I must have somehow placed while copying over the example code. There are no longer any matrix multiplication errors.

The only issue is that the code does not seem to ever stop running, even with a smaller sample of individuals. I'm figuring out how to look at this now as no error messages appear when this happens.

Thank you for the help as always,

Tim

**Comment by zilinli1988** [comment]
Hi Tim,

To boost the computation speed of SCANG, we recommend using an R version configured with the Intel Math Kernel Library. It will save you at least 4-5 times compared to the standard R version. Please see the updated instruction of SCANG. 

Thanks.

Sincerely,
Zilin
